import './js/refs.js';
import './js/axios.js';
import './js/preloader.js';
import './js/navigation.js';
import './js/popup.js';
import './js/form.js';
import './js/phone-mask.js';
import './js/scroll-to-block.js';
import './js/theme-switcher.js';
